services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    networks:
      - banknet
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ../auth-service
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - banknet
    ports:
      - "6000:8081"

  greeting-service:
    build: ../greeting-service
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - banknet
    ports:
      - "6001:8082"
  
  product-service:
    build: ../product-service
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - banknet
    ports:
      - "6002:8083"

  gateway-service:
    build: ../gateway-service
    depends_on:
      auth-service:
        condition: service_started
      greeting-service:
        condition: service_started
      product-service:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - banknet
    ports:
      - "8080:8080"

networks:
  banknet:
    driver: bridge
